---


- name: check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: create swap file
  become: true 
  command: fallocate -l 2G {{ swap_file }}
  when: not swap_file_check.stat.exists


- name: set permissions on swap file
  become: true
  file:
    path: "{{ swap_file }}"
    mode: 0600

- name: format swap file
  become: true
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: add to fstab
  become: true
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"

- name: turn on swap
  become: true
  command: swapon -a

- name: set memory management vm.overcommit_memory
  become: true
  sysctl:
    name: vm.overcommit_memory
    value: "1"
  notify: reboot

- name: check if a reboot is required
  shell: "[ -f /var/run/reboot-required ]"
  failed_when: False
  register: reboot_required
  changed_when: reboot_required.rc == 0
  notify: reboot
