---
#configure firewall for MN
#
- name: Setup ufw
  ufw: state=enabled policy=deny

- name: Allow ssh traffic on port 22
  ufw: 
    rule: allow
    proto: tcp
    port: ssh
  register: tcp_status
  changed_when: false
- debug: var=tcp_status

- name: Limit SSH
  ufw:
     rule: limit
     proto: tcp
     port: ssh
  #register: limitssh_status
  #changed_when: false
  #- debug: var=limitssh_status
  
- name: Allow Port 9999 traffic
  ufw: 
    rule: allow
    port: '9999'
    proto: tcp
  register: allowtcpport_status
  changed_when: false
- debug: var=allowtcpport_status

- name: Set logging
  ufw:
    logging: 'on'
    


