---    
# ansible playbook create-users.yml    
                                                                    
- name: Create a new {{ dash_user }} user                                     
  user:                                                           
    name: "{{ dash_user }}"                                                    
    state: present                                                
    password: passwd1234                                          
    shell: /bin/bash                                              
                                                                    
- name: Create {{ dashadmin_user }} User                                     
  user:                                                           
    name: "{{ dashadmin_user }}"                                               
    state: present                                                
    password: passwd1234                                          
    shell: /bin/bash

- name: Set authorized key for user {{ dashadmin_user }} copying it from current user
  authorized_key:
    user: "{{ dashadmin_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
       
- name: Set authorized key for user {{ dash_user }} copying it from current user
  authorized_key:
    user: "{{ dash_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
