---
- name: Update package cache
  package: update_cache=yes cache_valid_time=3600

- name: Upgrade to the latest packages
  package: upgrade=safe
  
- name: Install {{ required_packages }}
  package: 
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"


- name: "Install github3.py module to be able to use github_release module"
  pip:
    name:
      - github3.py
