---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade APT to the latest packages
  apt: upgrade=safe
  
- name: Install ufw, python, virtualenv, git, unzip, pv, speetest-cli
  apt: 
    name: 
      - ufw
      - python
      - virtualenv
      - git
      - unzip
      - pv
      - speedtest-cli
      - python-pip
    state: present


- name: "Install github3.py module to be able to use github_release module"
  pip:
    name:
      - github3.py
