---
# handlers file for /etc/ansible/roles/deploy-dashmasternode
#
- name: Restart ssh
  service: name=ssh state=restarted
  remote_user: "{{ dashadmin_user }}"
  become: yes

- name: restart dashd
  service: name=dashd state=restarted
  remote_user: "{{ dashadmin_user }}"
  become: yes

- name: reboot
  reboot:
  remote_user: "{{ dashadmin_user }}"
  become: yes

